import cx_Oracle

class OracleConnector:
    def __init__(self, user=None, password=None, dsn=None):
        self.user = user or 'seu_usuario'
        self.password = password or 'sua_senha'
        self.dsn = dsn or 'host:port/service_name'
        self.conn = None

    def connect(self):
        self.conn = cx_Oracle.connect(self.user, self.password, self.dsn)
        return self.conn

    def close(self):
        if self.conn:
            try:
                self.conn.close()
            except Exception:
                pass

    def criar_tabela_producao(self):
        sql = '''
        CREATE TABLE producao (
            id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
            tipo VARCHAR2(100),
            area_ha NUMBER,
            produtividade_t_ha NUMBER,
            perda_percentual NUMBER,
            PRIMARY KEY (id)
        )
        '''
        cur = self.conn.cursor()
        cur.execute(sql)
        cur.close()

    def inserir_producao(self, producao: dict):
        sql = "INSERT INTO producao (tipo, area_ha, produtividade_t_ha, perda_percentual) VALUES (:1, :2, :3, :4)"
        cur = self.conn.cursor()
        cur.execute(sql, (producao['tipo'], producao['area_ha'], producao['produtividade_t_ha'], producao['perda_percentual']))
        self.conn.commit()
        cur.close()
